apiVersion: v1
kind: Namespace
metadata:
  name: limits
---
apiVersion: v1
kind: Namespace
metadata:
  name: worst
---
apiVersion: v1
kind: Namespace
metadata:
  name: recommended
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoryeater
  namespace: limits
  labels:
    app: memoryeater
spec:
  replicas: 15
  selector:
    matchLabels:
      app: memoryeater
  template:
    metadata:
      labels:
        app: memoryeater
    spec:
      containers:
      - name: memoryeater
        image: gambtho/memoryeater:v2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1G"
            cpu: "250m"
          limits:
            memory: "2G"
            cpu: "500m"
        env:
        - name: JAVA_OPTS
          value: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoryeater
  namespace: worst
  labels:
    app: memoryeater
spec:
  replicas: 15
  selector:
    matchLabels:
      app: memoryeater
  template:
    metadata:
      labels:
        app: memoryeater
    spec:
      containers:
      - name: memoryeater
        image: gambtho/memoryeater:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoryeater
  namespace: recommended
  labels:
    app: memoryeater
spec:
  replicas: 15
  selector:
    matchLabels:
      app: memoryeater
  template:
    metadata:
      labels:
        app: memoryeater
    spec:
      containers:
      - name: memoryeater
        image: gambtho/memoryeater:v2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1G"
            cpu: "250m"
          limits:
            memory: "2G"
            cpu: "500m"

