apiVersion: v1
kind: Namespace
metadata:
  name: limits
---
apiVersion: v1
kind: Namespace
metadata:
  name: worst
---
apiVersion: v1
kind: Namespace
metadata:
  name: recommended
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoryeater
  namespace: limits
  labels:
    app: memoryeater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memoryeater
  template:
    metadata:
      labels:
        app: memoryeater
    spec:
      containers:
      - name: memoryeater-limits
        image: gambtho/memoryeater:v3.4.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1G"
            cpu: "250m"
          limits:
            memory: "2G"
            cpu: "500m"
        env:
        - name: SLEEP_PERIOD
          value: "100"
        volumeMounts:
        - mountPath: /app/dump
          name: dump-volume
      volumes:
      - name: dump-volume
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoryeater
  namespace: worst
  labels:
    app: memoryeater
spec:
  replicas: 15
  selector:
    matchLabels:
      app: memoryeater
  template:
    metadata:
      labels:
        app: memoryeater
    spec:
      containers:
      - name: memoryeater-worst
        image: gambtho/memoryeater:v3.4.2
        imagePullPolicy: IfNotPresent
        env:
        - name: SLEEP_PERIOD
          value: "100"
        - name: JAVA_OPTS
          value: "-Xmx32G -XX:HeapDumpPath=/app/dump -XX:+HeapDumpOnOutOfMemoryError"
        volumeMounts:
        - mountPath: /app/dump
          name: dump-volume
      volumes:
      - name: dump-volume
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoryeater
  namespace: recommended
  labels:
    app: memoryeater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memoryeater
  template:
    metadata:
      labels:
        app: memoryeater
    spec:
      containers:
      - name: memoryeater-recommended
        image: gambtho/memoryeater:v3.4.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1G"
            cpu: "250m"
          limits:
            memory: "2G"
            cpu: "500m"
        env:
        - name: SLEEP_PERIOD
          value: "100"
        - name: JAVA_OPTS
          value: "-XX:+UseCGroupMemoryLimitForHeap -XX:+UnlockExperimentalVMOptions -XX:HeapDumpPath=/app/dump -XX:+HeapDumpOnOutOfMemoryError"
        volumeMounts:
        - mountPath: /app/dump
          name: dump-volume
      volumes:
      - name: dump-volume
        emptyDir: {}


        